name: application_muito_foda
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  background_fetch: ^1.2.1
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  google_nav_bar: ^5.0.6
  intl: ^0.18.1
  mask_text_input_formatter: ^2.5.0
  permission_handler: ^11.0.1
  search_cep: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
