// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIoAO8F8HX3kteB1GpAVsdaDNLVq9Du6Q',
    appId: '1:729354138287:web:1808f3f02fb66bd07d1a5a',
    messagingSenderId: '729354138287',
    projectId: 'biblioteca-virtual-49cf0',
    authDomain: 'biblioteca-virtual-49cf0.firebaseapp.com',
    storageBucket: 'biblioteca-virtual-49cf0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcO98O7WPsw-30DaoUAEIk598qHakEKUM',
    appId: '1:729354138287:android:eaacfb3311520f287d1a5a',
    messagingSenderId: '729354138287',
    projectId: 'biblioteca-virtual-49cf0',
    storageBucket: 'biblioteca-virtual-49cf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJfePtteXLjAG8uB-GXwRlp_SpouFzvkE',
    appId: '1:729354138287:ios:d7cfbddc46b4ae117d1a5a',
    messagingSenderId: '729354138287',
    projectId: 'biblioteca-virtual-49cf0',
    storageBucket: 'biblioteca-virtual-49cf0.appspot.com',
    iosBundleId: 'com.example.applicationMuitoFoda',
  );
}
